/**
 * File `bxr_keyboard.h`.
 *
 * Copyright (c) 2026 nsix. All rights reserved.
 *
 * # Keyboard Input Handling
 *
 * `bxr_key_e` values are based on scancode (the physical location of the
 * key on the keyboard), not keycode (the character generated by the key press,
 * which can change based on keyboard layout and modifiers).
 *
 * To get the key value of the current keyboard layout, use `bxr_key_name` or
 * `bxr_key_name_ex` with the appropriate modifiers.
 */

#ifndef BXR_KEYBOARD_H_
#define BXR_KEYBOARD_H_

#include <SDL3/SDL.h>

typedef enum
{
  BXR_KEY_UNKNOWN = SDL_SCANCODE_UNKNOWN,

  BXR_KEY_A = SDL_SCANCODE_A,
  BXR_KEY_B = SDL_SCANCODE_B,
  BXR_KEY_C = SDL_SCANCODE_C,
  BXR_KEY_D = SDL_SCANCODE_D,
  BXR_KEY_E = SDL_SCANCODE_E,
  BXR_KEY_F = SDL_SCANCODE_F,
  BXR_KEY_G = SDL_SCANCODE_G,
  BXR_KEY_H = SDL_SCANCODE_H,
  BXR_KEY_I = SDL_SCANCODE_I,
  BXR_KEY_J = SDL_SCANCODE_J,
  BXR_KEY_K = SDL_SCANCODE_K,
  BXR_KEY_L = SDL_SCANCODE_L,
  BXR_KEY_M = SDL_SCANCODE_M,
  BXR_KEY_N = SDL_SCANCODE_N,
  BXR_KEY_O = SDL_SCANCODE_O,
  BXR_KEY_P = SDL_SCANCODE_P,
  BXR_KEY_Q = SDL_SCANCODE_Q,
  BXR_KEY_R = SDL_SCANCODE_R,
  BXR_KEY_S = SDL_SCANCODE_S,
  BXR_KEY_T = SDL_SCANCODE_T,
  BXR_KEY_U = SDL_SCANCODE_U,
  BXR_KEY_V = SDL_SCANCODE_V,
  BXR_KEY_W = SDL_SCANCODE_W,
  BXR_KEY_X = SDL_SCANCODE_X,
  BXR_KEY_Y = SDL_SCANCODE_Y,
  BXR_KEY_Z = SDL_SCANCODE_Z,

  BXR_KEY_0 = SDL_SCANCODE_0,
  BXR_KEY_1 = SDL_SCANCODE_1,
  BXR_KEY_2 = SDL_SCANCODE_2,
  BXR_KEY_3 = SDL_SCANCODE_3,
  BXR_KEY_4 = SDL_SCANCODE_4,
  BXR_KEY_5 = SDL_SCANCODE_5,
  BXR_KEY_6 = SDL_SCANCODE_6,
  BXR_KEY_7 = SDL_SCANCODE_7,
  BXR_KEY_8 = SDL_SCANCODE_8,
  BXR_KEY_9 = SDL_SCANCODE_9,

  BXR_KEY_RETURN    = SDL_SCANCODE_RETURN,
  BXR_KEY_ESCAPE    = SDL_SCANCODE_ESCAPE,
  BXR_KEY_BACKSPACE = SDL_SCANCODE_BACKSPACE,
  BXR_KEY_TAB       = SDL_SCANCODE_TAB,
  BXR_KEY_SPACE     = SDL_SCANCODE_SPACE,

  BXR_KEY_MINUS        = SDL_SCANCODE_MINUS,
  BXR_KEY_EQUALS       = SDL_SCANCODE_EQUALS,
  BXR_KEY_LEFTBRACKET  = SDL_SCANCODE_LEFTBRACKET,
  BXR_KEY_RIGHTBRACKET = SDL_SCANCODE_RIGHTBRACKET,
  BXR_KEY_BACKSLASH    = SDL_SCANCODE_BACKSLASH,
  BXR_KEY_SEMICOLON    = SDL_SCANCODE_SEMICOLON,
  BXR_KEY_APOSTROPHE   = SDL_SCANCODE_APOSTROPHE,
  BXR_KEY_GRAVE        = SDL_SCANCODE_GRAVE,
  BXR_KEY_COMMA        = SDL_SCANCODE_COMMA,
  BXR_KEY_PERIOD       = SDL_SCANCODE_PERIOD,
  BXR_KEY_SLASH        = SDL_SCANCODE_SLASH,

  BXR_KEY_CAPSLOCK = SDL_SCANCODE_CAPSLOCK,

  BXR_KEY_F1  = SDL_SCANCODE_F1,
  BXR_KEY_F2  = SDL_SCANCODE_F2,
  BXR_KEY_F3  = SDL_SCANCODE_F3,
  BXR_KEY_F4  = SDL_SCANCODE_F4,
  BXR_KEY_F5  = SDL_SCANCODE_F5,
  BXR_KEY_F6  = SDL_SCANCODE_F6,
  BXR_KEY_F7  = SDL_SCANCODE_F7,
  BXR_KEY_F8  = SDL_SCANCODE_F8,
  BXR_KEY_F9  = SDL_SCANCODE_F9,
  BXR_KEY_F10 = SDL_SCANCODE_F10,
  BXR_KEY_F11 = SDL_SCANCODE_F11,
  BXR_KEY_F12 = SDL_SCANCODE_F12,

  BXR_KEY_PRINTSCREEN = SDL_SCANCODE_PRINTSCREEN,
  BXR_KEY_SCROLLLOCK  = SDL_SCANCODE_SCROLLLOCK,
  BXR_KEY_PAUSE       = SDL_SCANCODE_PAUSE,

  BXR_KEY_INSERT   = SDL_SCANCODE_INSERT,
  BXR_KEY_HOME     = SDL_SCANCODE_HOME,
  BXR_KEY_PAGEUP   = SDL_SCANCODE_PAGEUP,
  BXR_KEY_DELETE   = SDL_SCANCODE_DELETE,
  BXR_KEY_END      = SDL_SCANCODE_END,
  BXR_KEY_PAGEDOWN = SDL_SCANCODE_PAGEDOWN,

  BXR_KEY_RIGHT = SDL_SCANCODE_RIGHT,
  BXR_KEY_LEFT  = SDL_SCANCODE_LEFT,
  BXR_KEY_DOWN  = SDL_SCANCODE_DOWN,
  BXR_KEY_UP    = SDL_SCANCODE_UP,

  BXR_KEY_NUMLOCKCLEAR = SDL_SCANCODE_NUMLOCKCLEAR,

  BXR_KEY_KP_DIVIDE   = SDL_SCANCODE_KP_DIVIDE,
  BXR_KEY_KP_MULTIPLY = SDL_SCANCODE_KP_MULTIPLY,
  BXR_KEY_KP_MINUS    = SDL_SCANCODE_KP_MINUS,
  BXR_KEY_KP_PLUS     = SDL_SCANCODE_KP_PLUS,
  BXR_KEY_KP_ENTER    = SDL_SCANCODE_KP_ENTER,
  BXR_KEY_KP_1        = SDL_SCANCODE_KP_1,
  BXR_KEY_KP_2        = SDL_SCANCODE_KP_2,
  BXR_KEY_KP_3        = SDL_SCANCODE_KP_3,
  BXR_KEY_KP_4        = SDL_SCANCODE_KP_4,
  BXR_KEY_KP_5        = SDL_SCANCODE_KP_5,
  BXR_KEY_KP_6        = SDL_SCANCODE_KP_6,
  BXR_KEY_KP_7        = SDL_SCANCODE_KP_7,
  BXR_KEY_KP_8        = SDL_SCANCODE_KP_8,
  BXR_KEY_KP_9        = SDL_SCANCODE_KP_9,
  BXR_KEY_KP_0        = SDL_SCANCODE_KP_0,
  BXR_KEY_KP_PERIOD   = SDL_SCANCODE_KP_PERIOD,

  BXR_KEY_SIZE = SDL_SCANCODE_COUNT
} bxr_key_e;

typedef enum
{
  BXR_KEYMOD_NONE   = SDL_KMOD_NONE,
  BXR_KEYMOD_LSHIFT = SDL_KMOD_LSHIFT,
  BXR_KEYMOD_RSHIFT = SDL_KMOD_RSHIFT,
  BXR_KEYMOD_LEVEL5 = SDL_KMOD_LEVEL5,
  BXR_KEYMOD_LCTRL  = SDL_KMOD_LCTRL,
  BXR_KEYMOD_RCTRL  = SDL_KMOD_RCTRL,
  BXR_KEYMOD_LALT   = SDL_KMOD_LALT,
  BXR_KEYMOD_RALT   = SDL_KMOD_RALT,
  BXR_KEYMOD_LGUI   = SDL_KMOD_LGUI,
  BXR_KEYMOD_RGUI   = SDL_KMOD_RGUI,
  BXR_KEYMOD_NUM    = SDL_KMOD_NUM,
  BXR_KEYMOD_CAPS   = SDL_KMOD_CAPS,
  BXR_KEYMOD_MODE   = SDL_KMOD_MODE,
  BXR_KEYMOD_SCROLL = SDL_KMOD_SCROLL,
  BXR_KEYMOD_CTRL   = SDL_KMOD_CTRL,
  BXR_KEYMOD_SHIFT  = SDL_KMOD_SHIFT,
  BXR_KEYMOD_ALT    = SDL_KMOD_ALT,
  BXR_KEYMOD_GUI    = SDL_KMOD_GUI,
} bxr_keymode_e;

/**
 * Internal API
 */

/**
 * Initialize the keyboard input system. Must be called before using any
 * other keyboard functions.
 */
void bxr_keyboard_setup(void);

/**
 * Update the keyboard state for the current frame. Must be called at the
 * beginning of each frame before processing input.
 */
void bxr_keyboard_begin_frame(void);

/**
 * Shutdown the keyboard input system. Must be called when the
 * application is closing to free any resources used by the keyboard system.
 */
void bxr_keyboard_shutdown(void);

/**
 * Handle a key down event for the given scancode. Must be called when a
 * key down event is received from SDL.
 *
 * `scancode` is the scancode of the key that was pressed.
 */
void bxr_key_down(bxr_key_e scancode);

/**
 * Handle a key up event for the given scancode. Must be called when a
 * key up event is received from SDL.
 *
 * `scancode` is the scancode of the key that was released.
 */
void bxr_key_up(bxr_key_e scancode);

/**
 * Public API
 */

/**
 * Get the name of a key based on its scancode and the current modifier state.
 *
 * Use the current modifier state to determine the key name.
 *
 * `key` is the scancode of the key to get the name of.
 *
 * `return` the name of the key, or "Unknown" if the key is not recognized.
 */
const char *bxr_key_name(bxr_key_e key);

/**
 * Get the name of a key based on its scancode and the given modifier state.
 *
 * `key` is the scancode of the key to get the name of.
 *
 * `mod` is the modifier state to use when determining the key name.
 *
 * `return` the name of the key, or "Unknown" if the key is not recognized.
 */
const char *bxr_key_name_ex(bxr_key_e key, bxr_keymode_e mod);

/**
 * Check if a key is currently held down.
 *
 * `key` is the scancode of the key to check.
 *
 * `return` true if the key is currently held down, false otherwise.
 */
bool bxr_key_held(bxr_key_e key);

/**
 * Check if a key was just pressed this frame.
 *
 * `key` is the scancode of the key to check.
 *
 * `return` true if the key was just pressed this frame, false otherwise.
 */
bool bxr_key_just_pressed(bxr_key_e key);

/**
 * Check if a key was just released this frame.
 *
 * `key` is the scancode of the key to check.
 *
 * `return` true if the key was just released this frame, false otherwise.
 */
bool bxr_key_just_released(bxr_key_e key);

/**
 * Get the amount of time a key has been held down.
 *
 * `key` is the scancode of the key to check.
 *
 * `return` the amount of time the key has been held down in milliseconds.
 */
Uint64 bxr_key_held_time(bxr_key_e key);

/**
 * Check if a specific modifier key is currently pressed.
 *
 * `mod` is the modifier key to check (e.g., BXR_KEYMOD_SHIFT, BXR_KEYMOD_CTRL).
 *
 * `return` true if the specified modifier key is currently pressed, false
 * otherwise.
 */
bool bxr_keymod_pressed(bxr_keymode_e mod);

#endif // BXR_KEYBOARD_H_
